# Generated by Django 5.2.3 on 2025-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('products_sold_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily sale summaries',
                'ordering': ['-summary_date'],
            },
        ),
    ]
